create temporary table DAS_API_ResponseSummaryData2 using CarbonJDBC options (dataSource "WSO2AM_STATS_DB", tableName "NEW_HOURLY_TABLE",
  schema "api STRING,
  api_version STRING,
  apiPublisher STRING,
  applicationName STRING,
  context STRING,
  method STRING,
  maxServiceTime INTEGER ,
  minServiceTime INTEGER ,
  serviceTime INTEGER ,
  maxBackendTime INTEGER ,
  minBackendTime INTEGER ,
  backendTime INTEGER ,
  total_response_count INTEGER ,
  hostName STRING ,
  year INTEGER ,
  month INTEGER ,
  day INTEGER,
  hour INTEGER,
  time STRING,
  resourceTemplate STRING",
  primaryKeys "api,api_version,apiPublisher,context,resourceTemplate,hostName,year,month,day"
  );


CREATE TEMPORARY TABLE APIMGT_HOURLY_RESPONSE_DATA USING CarbonJDBC OPTIONS(dataSource "WSO2AM_STATS_DB", tableName "EXISTING_HOURLY_TABLE",
  schema "api STRING,
  api_version STRING,
  apiPublisher STRING,
  applicationName STRING,
  context STRING,
  method STRING,
  maxServiceTime INTEGER ,
  minServiceTime INTEGER ,
  serviceTime INTEGER ,
  maxBackendTime INTEGER ,
  minBackendTime INTEGER ,
  backendTime INTEGER ,
  total_response_count INTEGER ,
  hostName STRING ,
  year INTEGER ,
  month INTEGER ,
  day INTEGER,
  hour INTEGER,
  time STRING,
  resourceTemplate STRING,
  resourcePath STRING"  ,
  primaryKeys "api,api_version,apiPublisher,context,resourceTemplate,applicationName,method,hostName,year,month,day,hour,resourcePath"
);

      insert into table DAS_API_ResponseSummaryData2 select
        api,
        api_version,
        apiPublisher,
        applicationName,
        context,
        method,
        max(maxServiceTime) as maxServiceTime,
        min(minServiceTime) as minServiceTime,
        avg(serviceTime) as serviceTime,
        max(maxBackendTime) as maxBackendTime,
        min(minBackendTime) as minBackendTime,
        avg(backendTime) as backendTime,
        sum(total_response_count) as total_response_count,
        hostName,
        year,
        month,
        day,
        hour,
        first(time) as time,
        resourceTemplate
    from APIMGT_HOURLY_RESPONSE_DATA
    group by api,api_version,apiPublisher,context,applicationName,method,hostName,year,month,day,hour,resourceTemplate;
